namespace FourPlayCharacterCreator
{
    public enum PsionicSpell
    {
        //Telepathy
        AllEyes,
        AlterEgo,
        BrainPressure,
        CallOfTheMind,
        Hallucination,
        OpenBook,
        ScrambledLobe,
        ThePurge,
        //Faith Healing
        Boost,
        Clarity,
        DeathTouch,
        OxLimb,
        Purification,
        Resurgat,
        Weakness,
        WoundSwap,
        //Temporalism
        BeamJump,
        Bilocation,
        DoubleTime,
        GhostMove,
        OldTimer,
        RemoteViewing,
        Snatch,
        TranportViaDoor,
        //Psychokinesis
        BatteringRam,
        BrainTornado,
        Elevator,
        HandOfForce,
        MightyHand,
        MIRV,
        Shield,
        Weave
    }
}
